function [f, bins] = bow_computeImageRep(I, model)
% Computes an image representation (of I) using the quantization 
% parameters in the model
% @param I : image after imread
% @param model : model as generated by bow_computeVocab
% @return : f (Same as from vl_sift) and bins = quantized descriptor values

bow_config;
try % to handle gray images
    I = rgb2gray(I); 
catch
end
I = single(I);
[f, d] = vl_sift(I);
bins = double(vl_kdtreequery(model.kdtree, model.vocab, double(d)));
